[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"

[tool.pytest.ini_options]
addopts = '--cov'
testpats = 'tests'

[tool.coverage.run]
source = ['scripts']
omit = ['tests/*']
